export type LegalSection = {
  title: string;
  updated?: string;
  sections: string[];
};

export const LEGAL_TEXT: Record<'terms' | 'privacy', LegalSection> = {
  terms: {
    title: 'Điều khoản sử dụng',
    sections: [
      'Ngày hiệu lực: 13/01/2026',
      'Bằng việc tải xuống, cài đặt hoặc sử dụng Asinu Lite, bạn đồng ý bị ràng buộc bởi Điều khoản này.',
      '1. Medical Disclaimer (Miễn trừ trách nhiệm y tế) – BẮT BUỘC',
      'ASINU LITE KHÔNG PHẢI THIẾT BỊ Y TẾ, KHÔNG PHẢI PHẦN MỀM CHẨN ĐOÁN, ĐIỀU TRỊ, HOẶC PHÒNG NGỪA BỆNH.',
      'Asinu Lite chỉ là công cụ ghi chép và theo dõi dữ liệu do bạn nhập.',
      'Mọi thông tin/biểu đồ/thống kê hiển thị chỉ nhằm mục đích tham khảo và quản lý cá nhân.',
      'Bạn phải tham khảo bác sĩ hoặc chuyên gia y tế có chuyên môn trước mọi quyết định liên quan đến sức khỏe, thuốc, chế độ điều trị.',
      'Trong trường hợp khẩn cấp, hãy liên hệ cơ sở y tế gần nhất.',
      '2. Trách nhiệm dữ liệu do người dùng nhập',
      'Bạn cam kết dữ liệu bạn nhập là đúng, đầy đủ và cập nhật theo thực tế.',
      'Bạn chịu trách nhiệm đối với hậu quả phát sinh từ việc nhập sai/thiếu hoặc sử dụng dữ liệu theo cách không phù hợp.',
      'Asinu Lite không chịu trách nhiệm nếu kết quả theo dõi bị sai lệch do dữ liệu đầu vào không chính xác.',
      '3. Tài khoản và bảo mật',
      'Bạn chịu trách nhiệm giữ bí mật thông tin đăng nhập.',
      'Nếu phát hiện truy cập trái phép, bạn cần thông báo ngay cho chúng tôi để hỗ trợ.',
      '4. Quyền sở hữu và giới hạn sử dụng',
      'Ứng dụng, giao diện, nội dung, nhãn hiệu thuộc quyền sở hữu của DIABOT (trừ các thành phần thuộc bên thứ ba được cấp phép).',
      'Bạn không được sao chép, sửa đổi, đảo ngược mã, khai thác trái phép hoặc sử dụng ứng dụng vào mục đích vi phạm pháp luật.',
      '5. Giới hạn trách nhiệm',
      'Trong phạm vi pháp luật cho phép:',
      'DIABOT không chịu trách nhiệm cho thiệt hại gián tiếp/phát sinh do việc sử dụng hoặc không thể sử dụng ứng dụng, hoặc do dữ liệu bạn nhập không chính xác.',
      'DIABOT không chịu trách nhiệm cho quyết định y tế dựa trên ứng dụng thay vì tư vấn chuyên môn.',
      '6. Chấm dứt và xóa tài khoản',
      'Bạn có thể ngừng sử dụng ứng dụng bất cứ lúc nào. Bạn có quyền yêu cầu Delete Account theo Chính sách quyền riêng tư. Việc xóa tài khoản sẽ xóa/ẩn danh hóa dữ liệu theo quy trình và nghĩa vụ lưu trữ hợp pháp (nếu có).',
      '7. Thay đổi điều khoản',
      'Chúng tôi có thể cập nhật Điều khoản theo thời gian. Phiên bản mới nhất sẽ được công bố trên website. Việc bạn tiếp tục sử dụng sau khi cập nhật được hiểu là bạn đồng ý với phiên bản mới.',
      '8. Liên hệ',
      'CÔNG TY CỔ PHẦN DIABOT',
      'Email: diabotaiagent@gmail.com',
      'SĐT: 0898888917',
      'Địa chỉ: 12A, Ngách 1/16, Ngõ 1 Thúy Lĩnh, P. Lĩnh Nam, TP. Hà Nội, Việt Nam'
    ]
  },
  privacy: {
    title: 'Chính sách quyền riêng tư',
    updated: 'Ngày hiệu lực: 13/01/2026',
    sections: [
      'Ứng dụng: Asinu Lite',
      'Đơn vị vận hành/Chủ quản dữ liệu: CÔNG TY CỔ PHẦN DIABOT (DIABOT JOINT STOCK COMPANY)',
      'Mã số doanh nghiệp: 0111234998',
      'Địa chỉ: 12A, Ngách 1/16, Ngõ 1 Thúy Lĩnh, P. Lĩnh Nam, TP. Hà Nội, Việt Nam',
      'Email hỗ trợ: diabotaiagent@gmail.com',
      'SĐT: 0898888917',
      'Chính sách này mô tả cách Asinu Lite thu thập, sử dụng, lưu trữ, chia sẻ và bảo vệ dữ liệu cá nhân và dữ liệu sức khỏe của bạn. Khi sử dụng ứng dụng, bạn xác nhận đã đọc, hiểu và đồng ý với nội dung chính sách này.',
      '1. Định nghĩa dữ liệu và vai trò pháp lý',
      'Dữ liệu cá nhân: thông tin gắn với hoặc giúp nhận diện một cá nhân.',
      'Dữ liệu cá nhân nhạy cảm: bao gồm dữ liệu về sức khỏe. (Trong Asinu Lite, dữ liệu sức khỏe do bạn nhập là dữ liệu nhạy cảm).',
      'DIABOT là Bên kiểm soát dữ liệu cá nhân (data controller) đối với dữ liệu được xử lý trong hệ thống Asinu Lite; các đối tác hạ tầng (nếu có) chỉ đóng vai trò hỗ trợ kỹ thuật theo thỏa thuận và yêu cầu bảo mật.',
      '2. Dữ liệu chúng tôi thu thập',
      'Asinu Lite thu thập dữ liệu theo 2 nhóm:',
      '(A) Dữ liệu sức khỏe do người dùng tự nhập (nhạy cảm):',
      'Đường huyết (Blood Glucose)',
      'Huyết áp (Blood Pressure)',
      'Cân nặng (Weight)',
      'Lượng nước uống (Water Intake)',
      '(B) Dữ liệu tài khoản/cơ bản để vận hành dịch vụ (nếu bạn tạo tài khoản):',
      'Thông tin đăng nhập/định danh tài khoản (ví dụ: số điện thoại/email theo cơ chế đăng ký bạn lựa chọn)',
      'Dữ liệu kỹ thuật tối thiểu phục vụ vận hành và bảo mật (nhật ký lỗi, thông tin thiết bị ở mức cần thiết để khắc phục sự cố)',
      'Bạn có thể lựa chọn không cung cấp một số dữ liệu, nhưng khi đó một số tính năng theo dõi/biểu đồ có thể không hoạt động đầy đủ.',
      '3. Căn cứ xử lý dữ liệu (Legal basis)',
      'Chúng tôi xử lý dữ liệu dựa trên:',
      'Sự đồng ý của bạn khi bạn chủ động nhập dữ liệu và sử dụng các tính năng theo dõi.',
      'Nhu cầu cung cấp dịch vụ theo yêu cầu của bạn (hiển thị biểu đồ, thống kê, lịch sử).',
      'Nghĩa vụ bảo mật và an toàn hệ thống để phòng chống gian lận, lỗi kỹ thuật.',
      'Bạn có quyền rút lại sự đồng ý bất cứ lúc nào; việc rút lại đồng ý có thể làm hạn chế một số chức năng.',
      '4. Mục đích sử dụng dữ liệu',
      'Dữ liệu được sử dụng để:',
      'Hiển thị biểu đồ và lịch sử theo dõi sức khỏe cá nhân',
      'Thống kê xu hướng theo thời gian (ngày/tuần/tháng)',
      'Cải thiện chất lượng ứng dụng và hỗ trợ người dùng (khắc phục lỗi, tối ưu trải nghiệm)',
      'Asinu Lite không bán dữ liệu và không khai thác dữ liệu sức khỏe để “kiếm tiền từ dữ liệu”.',
      '5. Chia sẻ dữ liệu với bên thứ ba',
      'Nguyên tắc:',
      'Không bán – không cho thuê – không trao đổi dữ liệu cá nhân/dữ liệu sức khỏe cho bên thứ ba.',
      'Chỉ chia sẻ dữ liệu trong các trường hợp tối thiểu sau:',
      'Nhà cung cấp hạ tầng kỹ thuật (lưu trữ/đám mây/email/giám sát lỗi) khi cần để vận hành dịch vụ, và các bên này phải tuân thủ yêu cầu bảo mật theo hợp đồng.',
      'Yêu cầu hợp pháp của cơ quan nhà nước có thẩm quyền theo quy định pháp luật.',
      'Bảo vệ quyền và lợi ích hợp pháp của DIABOT và người dùng trong trường hợp có tranh chấp/gian lận/vi phạm.',
      '6. Lưu trữ và thời hạn lưu trữ (Data retention)',
      'Dữ liệu được lưu trong suốt thời gian tài khoản của bạn còn hoạt động để bạn xem lại lịch sử và biểu đồ.',
      'Khi bạn yêu cầu xóa tài khoản, chúng tôi sẽ xóa hoặc ẩn danh hóa dữ liệu theo Mục 8 dưới đây, trừ phần dữ liệu mà pháp luật yêu cầu phải lưu (nếu có) hoặc cần thiết để giải quyết tranh chấp.',
      'Một số bản sao lưu kỹ thuật (backup) có thể tồn tại trong thời gian giới hạn theo chu kỳ sao lưu, sau đó sẽ tự động bị ghi đè/xóa.',
      '7. Bảo mật dữ liệu',
      'Chúng tôi áp dụng biện pháp bảo vệ hợp lý về kỹ thuật và tổ chức, ví dụ:',
      'Kiểm soát truy cập nội bộ theo phân quyền',
      'Mã hóa/kênh truyền an toàn (khi truyền dữ liệu)',
      'Giám sát và ghi nhận sự cố kỹ thuật để tăng an toàn hệ thống',
      'Tuy nhiên, không hệ thống nào an toàn tuyệt đối. Trong trường hợp xảy ra sự cố rò rỉ trái phép, chúng tôi sẽ thực hiện các bước xử lý theo quy định pháp luật và thông báo khi cần thiết.',
      '8. Quyền của người dùng (Data subject rights) & Delete Account',
      'Bạn có quyền:',
      'Xem, chỉnh sửa, cập nhật dữ liệu bạn đã nhập',
      'Yêu cầu truy cập/bản sao dữ liệu (trong phạm vi hệ thống cho phép)',
      'Rút lại đồng ý xử lý dữ liệu',
      'Yêu cầu xóa dữ liệu và xóa tài khoản (Delete Account)',
      'Delete Account – cách thực hiện:',
      'Trong ứng dụng: vào Cài đặt → Tài khoản → Xóa tài khoản và làm theo hướng dẫn. (Yêu cầu bắt buộc của Apple với app có tạo tài khoản).',
      'Hoặc liên hệ email: diabotaiagent@gmail.com với tiêu đề “Yêu cầu xóa tài khoản Asinu”.',
      'Sau khi xác minh đúng chủ tài khoản, chúng tôi sẽ tiến hành xóa/ẩn danh hóa dữ liệu theo quy trình nội bộ trong thời gian hợp lý.',
      '9. Dữ liệu trẻ em',
      'Asinu Lite hướng đến người trưởng thành. Nếu bạn là cha/mẹ/người giám hộ và cho phép trẻ em sử dụng, bạn chịu trách nhiệm về sự đồng ý và dữ liệu được nhập.',
      '10. Chuyển dữ liệu ra nước ngoài (nếu có)',
      'Trong trường hợp hạ tầng kỹ thuật đặt ngoài Việt Nam hoặc có xử lý xuyên biên giới, chúng tôi sẽ thực hiện theo quy định pháp luật Việt Nam về bảo vệ dữ liệu cá nhân và áp dụng biện pháp bảo mật phù hợp.',
      '11. Liên hệ',
      'Nếu có câu hỏi/khiếu nại liên quan quyền riêng tư, vui lòng liên hệ:',
      'DIABOT JOINT STOCK COMPANY – Email: diabotaiagent@gmail.com – SĐT: 0898888917'
    ]
  }
};
